### ISSUE TITLE
`rez_pip_version` metadata missing from produced package.py files

### ISSUE THREAD

**Issue by brycegbrazen** [JeanChristopheMorinPerso/rez-pip#76]
When running `rez-pip2` on any package, the `rez_pip_version` metadata is missing from the produced `package.py` file.

This metadata is shown to be present in the [docs](https://rez-pip.readthedocs.io/en/latest/metadata.html#extra-metadata-added-by-rez-pip) but does not appear in produced `package.py` files.

**Environment**
- Windows 10
- Rez version 2.112.0
- Rez python version 3.7
- rez-pip 0.3.1

**To Reproduce**
1. Install new `rez-pip`
2. `rez-pip2 semver==3.0.2` (can also try `requests==2.31.0` or any other package at all)

**Expected Behavior**
`rez_pip_version` metadata present in `pip` attribute of `package.py`.

**Actual Behavior**
`rez_pip_version` is missing from `pip` attribute of `package.py`

**Comment by brycegbrazen** [comment]
Looks like we need to add a tiny bit of new code [here](https://github.com/JeanChristopheMorinPerso/rez-pip/blob/0.3.1/src/rez_pip/rez.py#L116).

@JeanChristopheMorinPerso mentioned we could just get the current version with `importlib_metadata.version('rez-pip')`

**Comment by JeanChristopheMorinPerso** [comment]
This is fixed in the latest version.
