### ISSUE TITLE
Installs for multiple pythons?

### ISSUE THREAD

**Issue by czerouni** [JeanChristopheMorinPerso/rez-pip#82]
When I issue this command:
```
rez-pip2 --pip <path/to/pip.pyz> --python-version 3.9 pyRXP==3.0.1
```
what happens is that it seems to want to go through all the versions of 3.9 that are installed, so I get
```
Installing requested packages for Python 3.9.13
...
Installing requested packages for Python 3.9.16
...
etc
```
Is this expected? Is there a way to not have it do this?

**Comment by JeanChristopheMorinPerso** [comment]
Hi, thanks for opening this issue. It's working as expected. I don't have multiple patch revisions of the same minor in my local dev environment, so it just never occurred to me. But I see how it can be surprising.

I think it should be changed to install for every major+minor only. Anyway I don't think there is going to be much need to install stuff for every single major+minor+patch.

Would that work for you?

**Comment by JeanChristopheMorinPerso** [comment]
In the meantime, you can use `--python-version ==3.9.16`.

**Comment by czerouni** [comment]
Yes, major.minor is what I would expect. Thanks for the quick response!
